name: pin_lock

version: 0.1.0

description: "A full solution to local authentication: it contains authentication logic and tracks authentication-relevant data, while providing an interface for app-specific UI implementatin."

repository: https://github.com/DutchCodingCompany/pin_lock

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  flutter_bloc: ^9.1.1
  equatable: ^2.0.3
  local_auth: ^2.1.3
  crypto: ^3.0.1
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  mockito: ^5.3.2

flutter:
  plugin:
    platforms:
      android:
        package: nl.dutchcodingcompany.pin_lock
        pluginClass: PinLockPlugin
      ios:
        pluginClass: PinLockPlugin
